CREATE TABLE IF NOT EXISTS producers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS studios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    nomination_year INT NOT NULL,
    winner BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_producers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    film_id BIGINT NOT NULL,
    producer_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_studios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    film_id BIGINT NOT NULL,
    studio_id bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS film_producers ADD CONSTRAINT fk_film_producers_film_id     FOREIGN KEY (film_id)     REFERENCES films;
ALTER TABLE IF EXISTS film_producers ADD CONSTRAINT fk_film_producers_producer_id FOREIGN KEY (producer_id) REFERENCES producers;

ALTER TABLE IF EXISTS film_studios ADD CONSTRAINT fk_film_studios_film_id   FOREIGN KEY (film_id)   REFERENCES films;
ALTER TABLE IF EXISTS film_studios ADD CONSTRAINT fk_film_studios_studio_id FOREIGN KEY (studio_id) REFERENCES studios;
